# Generated by Django 4.1.2 on 2022-10-30 10:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SendMail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.UUID('467f98c7-eb74-409a-9e0f-8701e809aa1b'), editable=False)),
                ('to', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('attachment', models.FileField(blank=True, upload_to='')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
