# Generated by Django 4.1.2 on 2022-10-30 14:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_sendmail_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sendmail',
            name='attachment',
        ),
        migrations.AlterField(
            model_name='sendmail',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('486d3b22-bcb0-40f7-8502-bbdac3cb128f'), editable=False),
        ),
    ]
